import {
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronLeftIcon,
  MagnifyingGlassIcon,
  XMarkIcon,
  CalendarIcon,
  HeartIcon,
  ClockIcon,
  UserIcon,
  SparklesIcon,
  SunIcon,
  ScaleIcon,
  HomeIcon,
  EnvelopeIcon,
  PhoneIcon,
} from "@heroicons/react/24/outline";

export {
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronLeftIcon,
  MagnifyingGlassIcon,
  XMarkIcon,
  CalendarIcon,
  HeartIcon,
  ClockIcon,
  UserIcon,
  SparklesIcon,
  SunIcon,
  ScaleIcon,
  HomeIcon,
  EnvelopeIcon,
  PhoneIcon,
};
